"""initial migration

Revision ID: ea4627f8a78d
Revises: 
Create Date: 2025-04-18 19:49:46.201634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4627f8a78d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('computer_component_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_computer_component_categories_id'), 'computer_component_categories', ['id'], unique=False)
    op.create_table('purchase_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_invoice_no', sa.String(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sum_total_line_amounts', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_invoice_no')
    )
    op.create_table('computer_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_code', sa.String(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=20, scale=6), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['computer_component_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('product_code')
    )
    op.create_index(op.f('ix_computer_components_id'), 'computer_components', ['id'], unique=False)
    op.create_table('purchase_invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_invoice_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('component_name', sa.String(), nullable=False),
    sa.Column('component_category_id', sa.Integer(), nullable=False),
    sa.Column('component_category_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('total_line_amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['component_category_id'], ['computer_component_categories.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['computer_components.id'], ),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_invoice_lines')
    op.drop_index(op.f('ix_computer_components_id'), table_name='computer_components')
    op.drop_table('computer_components')
    op.drop_table('purchase_invoices')
    op.drop_index(op.f('ix_computer_component_categories_id'), table_name='computer_component_categories')
    op.drop_table('computer_component_categories')
    # ### end Alembic commands ###
