# version: "3.9"
# pisgop (people shop good price)

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
  fastapi:
    build: ./fastapi-service
    container_name: 'pisgop-fastapi'
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-service:/app
    environment:
      - DB_HOST=${DB_STAGING_HOST}
      - DB_PORT=${DB_STAGING_PORT}
      - DB_USER=${DB_STAGING_USERNAME}
      - DB_PASSWORD=${DB_STAGING_PASSWORD}
      - DB_NAME=${DB_STAGING_DATABASE}
      - DEBUG=False # Disable debug mode in production
      - WEB_ENVIRONMENT=${WEB_ENVIRONMENT}
    command: python main.py
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://fastapi:8000/" ]
      interval: 40s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - .env
  fastapi-celery:
    build: ./fastapi-service
    container_name: 'pisgop-fastapi-celery'
    ports:
      - "5678:5678"
    command: celery -A src.api.routers.payment worker --loglevel=info
    volumes:
      - ./fastapi-service:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    depends_on:
      - fastapi
      - redis
    networks:
      - app-network
    env_file:
      - .env
  rails:
    build:
      context: ./rails-service
      dockerfile: Dockerfile.dev
      shm_size: '2gb'
    container_name: 'pisgop-rails'
    environment:
      - RAILS_ENV=development
      - DB_STAGING_HOST=db
      - DB_STAGING_PORT=5432
      - DB_STAGING_DATABASE=${DB_STAGING_DATABASE}
      - DB_STAGING_USERNAME=${DB_STAGING_USERNAME}
      - DB_STAGING_PASSWORD=${DB_STAGING_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./rails-service:/app
      - ./rails-service:/app:cached
      - /app/tmp
      - /app/log
      - bundle_cache:/usr/local/bundle
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/up" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    env_file:
      - .env
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.local.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/static:ro
    depends_on:
      - rails
      - fastapi
    networks:
      - app-network
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_STAGING_USERNAME}
      POSTGRES_PASSWORD: ${DB_STAGING_PASSWORD}
      POSTGRES_DB: ${DB_STAGING_DATABASE}
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume:
  redis_data:
  bundle_cache:


networks:
  app-network:
    driver: bridge
